# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Josie Huang
name: Josie Huang

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar

#Specific contents
navbar-title: Josie Huang

#Navigation bar links
navbar-links:
- title: Home
  url: index.html
- title: CV
  url: /
- title: Publications
  url: publications.html
- title: ASH Labpage
  url: http://wilsonlab.la.psu.edu
- title: Novel Project
  url: novel.html

#Introduction
intro_text: I am a second-year PhD student majoring in Clinical Psychology at The Penn State University, State College. I am currently working with <a href="http://psych.la.psu.edu/directory/sjw42">Dr. Stephen Wilson</a> on a project that examines the impacts of contextual information on the neural and subjective reactivity to food and non-food reward cues in indivivduals with eating regulatory difficulties. Our goal is to identify the neural markers that predict motivational dysfunctions and over-eating behaviors in an obesogenic environment replete with energy-dense, highly palatable food. We expect that these results will become one important contribution to the long line of the research in our lab that is aimed at developing a better understanding of the cognitive, affective, and motivational factors for addiction and overconsumption behaviors. <br/><br/> Aside from research, I am also trained and practice clinical assessment, diagnosis, and psychotherapy at the clinic at PSU. 

#Education
positions:
- degree: Ph.D. candidate in Clinical Psychology
  year: 2017-present
  university: The Penn State University
  research: The effects of perceived eating opportunity on reward processing and food choices in individuals with difficulties controlling overeating.
- degree: M.A. (Psychology)
  year: 2014-2017
  university: San Diego State University
  research: Temporal-spatial characteristics of cognitive and affective functions in alcohol abuse.
- degree: B.S. (Psychology)
  year: 2008-2012
  university: Peking University
  research: The modulating effects of group membership on empathic neural responses.

#Contact info
contact:
- title: Email <br/> suh438@psu.edu 
  url: mailto:suh438@psu.edu
- title: Address <br/>407 Moore Building, University Park, State College, PA 16802

  
#Program Skills
programskills:
- MATLAB
- R
- STATA
- Presentation
- E-Prime
- SPSS
- HTML

#Neuroscience Skills
neuroskills:
- title: Fieldtrip (EEG & MEG)
  url: http://www.fieldtriptoolbox.org
- title: FSL (MRI)
  url: https://fsl.fmrib.ox.ac.uk/fsl/fslwiki
- title: fMRIPrep
  url: http://fmriprep.readthedocs.io/en/latest/usage.html
 
# Publication List
publications:
- title: <b>Huang. S.</b>, Holcomb, L. A., Cruz, S. M., & Marinkovic, K. (2018). Altered oscillatory brain dynamics of emotional processing in young binge drinkers. <i>Cognitive and Affective Behavioral Neuroscience, 18</i>(1) , 43-57. 
  url: https://link.springer.com/article/10.3758/s13415-017-0551-7
- title: Affan, R. O., <b>Huang, S.</b>, Cruz, S. M., Holcomb, L. A., Nguyen, E., & Marinkovic, K. (2018). High-intensity binge drinking is associated with alterations in spontaneous neural oscillations in young adults. <i>Alcohol, 70</i>, 51-60. 
  url: https://www.sciencedirect.com/science/article/pii/S0741832917308686 
- title: Molnar, S. M., Beaton, L. E., Happer, J. P., Holcomb, L. A., <b> Huang, S.</b>, Arienzo, D., & Marinkovic, K. (2018). Behavioral and brain activity indices of cognitive control deficits in binge drinkers. <i>Brain Sciences, 8</i>(1), 9.
  url: http://www.mdpi.com/2076-3425/8/1/9
- title: <b>Huang, S.</b>, Fan F., Zhang, Y., Yao, N., & Rodriguez, M. (2017). Attentional training for social anxiety in Chinese college students. <i> Chinese Journal of Clinical Psychology, 5 </i>, 986-990. 
- title: Zhang, N., Fan, F., <b>Huang, S.</b>, & Rodriguez, M. (2016). Mindfulness training for loneliness among Chinese college students - A pilot randomized controlled trial. <i>International Journal of Psychology</i>.  
  url: https://onlinelibrary.wiley.com/doi/abs/10.1002/ijop.12394
- title: <b>Huang, S.</b>, & Han, S. (2014). Shared beliefs enhance shared feelings - Religious/irreligious identifications modulate empathic neural responses. <i> Social Neuroscience, 9</i>(6), 639-649. 
  url: https://www.tandfonline.com/doi/abs/10.1080/17470919.2014.934396


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

